name: Robot Framework Tests

on:
  push:
    branches:
      - main
      - develop  # Adjust the branch as needed
  schedule:
    - cron: '0 0 */2 * *' # Schedule to run every two days

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    # Add a step to check Chrome installation
    - name: Check Chrome Installation
      run: google-chrome --version

    - name: Install Google Chrome
      run: |
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo dpkg -i google-chrome-stable_current_amd64.deb
      if: success()  # Only install if the previous step was successful

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install robotframework robotframework-seleniumlibrary

    - name: Run Robot Framework Tests
      run: |
        robot -d results --variable USERNAME:$USERNAME --variable PASSWORD:$PASSWORD --variable BROWSER:headlesschrome ./Formsflow-RobotFramework/test-cases/login.robot
      env:
        ROBOT_SYSLOG_FILE: ${{github.workspace}}/output.xml
        
    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: robot-results
        path: results/

    - name: Post to a Slack channel
      id: slack
      uses: Ilshidur/action-slack@2.1.0
      with:
        # Slack channel id, channel name, or user id to post message.
        # See also: https://api.slack.com/methods/chat.postMessage#channels
        # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
        channel-id: C063RFBM6KS
        # For posting a simple plain text message
        slack-message: "GitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
