name: Robot Framework Tests

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    # Add a step to check Chrome installation
    - name: Check Chrome Installation
      run: google-chrome --version

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install robotframework robotframework-seleniumlibrary

    # Add a step to run Robot Framework tests with xvfb (headless mode)
    - name: Run Robot Framework tests with xvfb
      run: xvfb-run robot -d results /home/runner/work/forms-flow-ai-automation-testing/forms-flow-ai-automation-testing/Formsflow-BundleRobot/test-cases/*.robot

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: robot-results
        path: results
