name: Robot Framework Tests

on:
  push:
    branches:
      - main
      - develop  # Adjust the branch as needed
  schedule:
    - cron: '0 0 */2 * *' # Schedule to run every two days

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    # Add a step to check Chrome installation
    - name: Check Chrome Installation
      run: google-chrome --version

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install robotframework robotframework-seleniumlibrary

    - name: Run Robot Framework
      run: robot -d results FormsflowRobotFramework/test-cases/*.robot 
        
      env:
        ROBOT_SYSLOG_FILE: ${{github.workspace}}/output.xml

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: robot-results
        path: results/

    - name: Notify on success or failure
      if: always()
      uses: Ilshidur/action-slack@2.1.0
      with:
        status: ${{ job.status }}
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
