name: Robot Framework Tests

on:
  push:
    branches:
      - main
      - develop  # Adjust the branch as needed
  schedule:
    - cron: '0 0 */2 * *' # Schedule to run every two days

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install robotframework robotframework-seleniumlibrary

    - name: Run Robot Framework Tests
      run: |
        robot -d results ./Formsflow-RobotFramework/test-cases/*.robot
      env:
        ROBOT_SYSLOG_FILE: ${{github.workspace}}/output.xml
        
    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: robot-results
        path: results/
